### PR TITLE
Langmuir

### PR DESCRIPTION
**Pull request by bolding**
As we are waiting for Knut to get 2FA I'll create the PR on his behalf.

### CODE REVIEW

**Comment by bolding** [comment]
If merged in it will likely create issues with GA as YAML files for cases are not updated.

In addition - are there configurations available for testing the new code.

**Comment by jornbr** [comment]
Regarding GA - it looks like all the checks completed successfully already?

**Comment by bolding** [comment]
Yes - but entries are added to the YAML file. And if cases are not updated how can they read them - and use some of the new settings?

**Comment by knutaros** [comment]
I only added the new option quasi_eq_h15 to the existing entry
scnd_method:
https://github.com/gotm-model/code/pull/52/files#diff-c48e6470fdfda065545361404b8db40451c037e8559d552ffc59ae02c792a4e6R759

**Comment by bolding** [comment]
But none of the existing cases will use that setting! So the GA will not test the new code at all - or did I misunderstand something.

**Pull request merged**
