### PR TITLE
support missing output.yaml (for the time being)

### PR DESCRIPTION
**Pull request by knutaros**

### CODE REVIEW

**Comment by bolding** [comment]
Hi Knut

What is the aim of the PR? And what problem does it solve?

Karsten

**Comment by knutaros** [comment]
Hi Karsten,

ERROR without fix:

     init_gotm_fabm_input
At line 47 of file
/media/work/kklingbe/tools/gotm/GOTMDIR/src/gotm/deprecated_output.F90
(unit = 10, file = 'fort.10')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7f0cba06fd1d in ???
#1  0x7f0cba070825 in ???
#2  0x7f0cba070f79 in ???
#3  0x7f0cba133dc3 in ???
#4  0x7f0cba134ccb in ???
#5  0x7f0cba137117 in ???
#6  0x7f0cba137278 in ???
#7  0x56306725ec34 in deprecated_output_
     at
/media/work/kklingbe/tools/gotm/GOTMDIR/src/gotm/deprecated_output.F90:47


Yes, I know if I transform my old nml first into yaml, than the error
would not occur (but then I also would have no output at all).
As long as GOTM supports the old nmls, there should be no error, right?
The problem is that now there is no file open before the nml is read.

Cheers, Knut

**Comment by bolding** [comment]
So to understand it correctly - if you run a nml-based setup and don't have an output section in the .nml file you get the error - or?

I still don't know what is to be fixed.

**Comment by knutaros** [comment]
On 6/18/20 8:54 AM, Karsten Bolding wrote:
>
> So to understand it correctly - if you run a nml-based setup and don't
> have an output section in the .nml file you get the error - or?
>
> I still don't know what is to be fixed.
>
nml-based and no output.yaml. Therefore entering deprecated output, but
there the open(gotmrun.nml) is missing before the read(output).

BTW: do I have to manually cc to you, or is this done on the github side?

**Comment by bolding** [comment]
If there are no side effects - please merge it in.

**Comment by jornbr** [comment]
Seems a bit clunky to re-open gotmrun.nml. Why don't we reorder gotm.F90 a little to have the call to deprecated_output come earlier, when gotmrun is still open?

Cheers,

Jorn

**Comment by bolding** [comment]
Jorns suggestion is also fine with me - but we should really move away from nml configuration. Then fixes like this would not be necessary.

The main show-stopper is like the lack of scriptable YAML configuration - similar to editscenario.

**Comment by knutaros** [comment]
On 6/18/20 10:18 AM, Karsten Bolding wrote:
>
> Jorns suggestion is also fine with me - but we should really move away
> from nml configuration. Then fixes like this would not be necessary.
>
right. because the read_nml part will go away one day, I did not
re-order as suggested. Because even without nml_read the functionality
of deprecated_output might be desired (to have some default output if no
specific output.yaml is present)(?)

**Comment by jornbr** [comment]
Ok fine with me. I looked briefly at reordering gotm.F90, but that is not entirely trivial. By all means merge in what you have

Cheers

Jorn

**Pull request merged**
